---
- name: Configure Dotfiles
  hosts: all
  connection: local
  vars_files:
    - vars/all.yml
  pre_tasks:
    - import_tasks: tasks/pretasks.yml
  roles:
    - role: homedirs
    - role: xdg
    - role: git
    - role: ssh
    - role: zsh
    - role: vim
    - role: tmux
    - role: tldr
    - role: flameshot
    - role: zathura
    - role: gtk
    - role: gnome
