---
- name: Configure Dotfiles
  hosts: all
  connection: local
  vars_files:
    - vars/all.yml
  roles:
    - role: zsh
    - role: git
    - role: tmux
    - role: neovim
    - role: tilix
    - role: flameshot
    - role: gnome
