---

#
# Set variables based on selected target
#

- name: Set vars for Desktop target
  set_fact:
    font_scaling_factor: 1.1500000000000001
    gnome_terminal_columns: 140
    gnome_terminal_rows: 36
  when: target == "desktop"
  tags:
    - always

- name: Set vars for Laptop target
  set_fact:
    font_scaling_factor: 1.0
    gnome_terminal_columns: 120
    gnome_terminal_rows: 30
  when: target == "laptop"
  tags:
    - always
