---
- name: Create VS Code config directories
  file:
    path: ~/.config/Code/User
    state: directory
    mode: '700'
  tags:
    - vscode

- name: Push user settings
  copy:
    src: "{{ item }}"
    dest: ~/.config/Code/User
    mode: '600'
  with_fileglob: 'files/*.json'
  tags:
    - vscode

- name: Install VS Code extensions
  command:
    cmd: code --install-extension {{ item }}
    creates: ~/.vscode/extensions/{{ item }}*
  loop: "{{ extensions }}"
  tags:
    - vscode
