---
- name: Create Zsh config directory
  file:
    path: ~/.config/zsh
    state: directory
    mode: '700'
  tags:
    - zsh

- name: Push Zsh config
  copy:
    src: zshrc
    dest: ~/.zshrc
    mode: '600'
  tags:
    - zsh

- name: Push extra config files
  copy:
    src: "{{ item }}"
    dest: ~/.config/zsh/{{ item }}
    mode: '600'
  loop:
    - aliases
    - functions
    - ctf
  tags:
    - zsh
