---
- name: Create Zsh config directory
  file:
    path: ~/.config/zsh
    state: directory
    mode: '700'
  tags:
    - zsh

- name: Push Zsh config
  copy:
    src: zshrc
    dest: ~/.zshrc
    mode: '600'
  tags:
    - zsh

- name: Push aliases file
  copy:
    src: aliases
    dest: ~/.config/zsh/aliases
    mode: '600'
  tags:
    - zsh
