---
- name: Push XDG's user-dirs config files
  copy:
    src: "{{ item }}"
    dest: ~/.config
    mode: '600'
  with_fileglob: 'files/user-dirs.*'
  tags:
    - xdg

- name: Push MIME applications list
  copy:
    src: mimeapps.list
    dest: ~/.config/mimeapps.list
    mode: '600'
  tags:
    - xdg
