---

#
# Dash to Dock
#

- name: Set Dash to Dock background color
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/background-color"
    value: "'{{ color.bg }}'"
  tags:
    - gnome

- name: Set Dash to Dock transparency mode to 'FIXED'
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/transparency-mode"
    value: "'FIXED'"
  tags:
    - gnome

- name: Set Dash to Dock background opacity
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/background-opacity"
    value: "0.35000000000000003"
  tags:
    - gnome
