---

- name: Set Gnome Terminal profile ID variables
  set_fact:
    default_terminal_profile_id: "b1dcc9dd-5262-4d8d-a863-c897e6d979b9"
    alternate_terminal_profile_id: "fc17965e-b405-4c00-8ac6-3eee97ecee05"
  tags:
    - gnome

- name: Configure Gnome Terminal (Default Profile)
  include_tasks: gnome_terminal_settings.yml
  vars:
    profile:
      name: "Default"
      id: "{{ default_terminal_profile_id }}"
      transparency: 10
  tags:
    - gnome

- name: Configure Gnome Terminal (Alternate Profile)
  include_tasks: gnome_terminal_settings.yml
  vars:
    profile:
      name: "Alternate"
      id: "{{ alternate_terminal_profile_id }}"
      transparency: 0
  tags:
    - gnome

- name: Enable Default and Alternate profiles for Gnome Terminal
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/list"
    value: "['{{ default_terminal_profile_id }}', '{{ alternate_terminal_profile_id }}']"
  tags:
    - gnome
