---

#
# Gnome Terminal Settings
#

- name: Set terminal default size (columns)
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:{{ profile.id }}/default-size-columns"
    value: "{{ gnome_terminal_columns }}"
  tags:
    - gnome

- name: Set terminal default size (rows)
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:{{ profile.id }}/default-size-rows"
    value: "{{ gnome_terminal_rows }}"
  tags:
    - gnome

- name: Disable terminal bell
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:{{ profile.id }}/audible-bell"
    value: "false"
  tags:
    - gnome

- name: Hide scrollbar
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:{{ profile.id }}/scrollbar-policy"
    value: "'never'"
  tags:
    - gnome

- name: Enable custom font
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:{{ profile.id }}/use-system-font"
    value: "false"
  tags:
    - gnome

- name: Set custom font type and size
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:{{ profile.id }}/font"
    value: "'JetBrains Mono 10'"
  tags:
    - gnome

# Required so that we can set our own custom colors
- name: Disable theme colors
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:{{ profile.id }}/use-theme-colors"
    value: "false"
  tags:
    - gnome

- name: Set background color
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:{{ profile.id }}/background-color"
    value: "'{{ color.normal.black }}'"
  tags:
    - gnome

- name: Set foreground color
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:{{ profile.id }}/foreground-color"
    value: "'{{ color.normal.green }}'"
  tags:
    - gnome

- name: Set background transparency
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:{{ profile.id }}/background-transparency-percent"
    value: "{{ profile.transparency }}"
  tags:
    - gnome

- name: Rename default profile
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:{{ profile.id }}/visible-name"
    value: "'{{ profile.name }}'"
  tags:
    - gnome
