---
- name: Enable two finger scrolling
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/two-finger-scrolling-enabled"
    value: "true"
  tags:
    - gnome

- name: Enable tap to click
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click"
    value: "true"
  tags:
    - gnome
