---

# Reference: https://gist.github.com/carlwgeorge/c560a532b6929f49d9c0df52f75a68ae

#
# Settings
#

- name: Create `~/.local/share/backgrounds`
  file:
    path: ~/.local/share/backgrounds
    state: directory
    mode: '700'
  tags:
    - gnome

- name: Download wallpaper
  get_url:
    url: "{{ wallpaper.url }}"
    dest: "{{ wallpaper.dest }}/{{ wallpaper.url | basename }}"
    checksum: "{{ wallpaper.checksum }}"
    mode: '600'
  tags:
    - gnome

- name: Set wallpaper
  block:
  - name: Set path to wallpaper
    set_fact:
      wallpaper_path: "'file:///usr/share/backgrounds/hak/art/7f87f27ad29252ecfc0d_3641x2017.jpg'"

  - name: Set wallpaper for Light Theme
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "{{ wallpaper_path}}"

  - name: Set wallpaper for Dark Theme
    dconf:
      key: "/org/gnome/desktop/background/picture-uri-dark"
      value: "{{ wallpaper_path}}"
  tags:
    - gnome

- name: Detach modal dialogs
  dconf:
    key: "/org/gnome/mutter/attach-modal-dialogs"
    value: "false"
  tags:
    - gnome

- name: Disable hot corners
  dconf:
    key: "/org/gnome/desktop/interface/enable-hot-corners"
    value: "false"
  tags:
    - gnome

- name: Set font scaling factor
  dconf:
    key: "/org/gnome/desktop/interface/text-scaling-factor"
    value: "{{ font_scaling_factor }}"
  tags:
    - gnome

- name: Set keyboard layout to US International
  dconf:
    key: "/org/gnome/desktop/input-sources/sources"
    value: "[('xkb', 'us+intl')]"
  tags:
    - gnome

- name: Dont't show notifications on lock screen
  dconf:
    key: "/org/gnome/desktop/notifications/show-in-lock-screen"
    value: "false"
  tags:
    - gnome

- name: Set favorite apps
  dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['org.gnome.Terminal.desktop', 'google-chrome.desktop', 'firefox-esr.desktop', 'org.gnome.gedit.desktop', 'wireshark.desktop', 'kali-burpsuite.desktop', 'bitwarden.desktop', 'obsidian.desktop', 'code.desktop', 'org.gnome.Nautilus.desktop']"
  tags:
    - gnome

- name: Enable Dash to Dock custom background color
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/custom-background-color"
    value: "true"
  tags:
    - gnome

- name: Configure shortcuts
  include_tasks: shortcuts.yml
  tags:
    - gnome

- name: Configure Gnome Terminal
  include_tasks: gnome_terminal.yml
  tags:
    - gnome

- name: Configure Dash to Dock
  include_tasks: dock.yml
  tags:
    - gnome

- name: Add Laptop specific tasks
  include_tasks: laptop.yml
  when: target is defined and target == "laptop"
  tags:
    - gnome

- name: Add Desktop specific tasks
  include_tasks: desktop.yml
  when: target is defined and target == "desktop"
  tags:
    - gnome
