---

# Reference: https://gist.github.com/carlwgeorge/c560a532b6929f49d9c0df52f75a68ae

#
# Settings
#

- name: Create `~/.local/share/backgrounds`
  file:
    path: ~/.local/share/backgrounds
    state: directory
    mode: '700'
  tags:
    - gnome

- name: Download wallpaper
  get_url:
    url: "{{ wallpaper.url }}"
    dest: "{{ wallpaper.dest }}/{{ wallpaper.url | basename }}"
    checksum: "{{ wallpaper.checksum }}"
    mode: '600'
  tags:
    - gnome

- name: Set wallpaper
  dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///{{ wallpaper.dest | expanduser }}/{{ wallpaper.url | basename }}'"
  tags:
    - gnome

- name: Detach modal dialogs
  dconf:
    key: "/org/gnome/mutter/attach-modal-dialogs"
    value: "false"
  tags:
    - gnome

- name: Disable hot corners
  dconf:
    key: "/org/gnome/desktop/interface/enable-hot-corners"
    value: "false"
  tags:
    - gnome

- name: Set font scaling factor
  dconf:
    key: "/org/gnome/desktop/interface/text-scaling-factor"
    value: "{{ font_scaling_factor }}"
  tags:
    - gnome

- name: Set keyboard layout to US International
  dconf:
    key: "/org/gnome/desktop/input-sources/sources"
    value: "[('xkb', 'us+intl')]"
  tags:
    - gnome

- name: Dont't show notifications on lock screen
  dconf:
    key: "/org/gnome/desktop/notifications/show-in-lock-screen"
    value: "false"
  tags:
    - gnome

- name: Set favorite apps
  dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "[\
      'com.gexperts.Tilix.desktop',\
      'google-chrome.desktop',\
      'firefox-esr.desktop',\
      'org.gnome.gedit.desktop',\
      'wireshark.desktop',\
      'kali-burpsuite.desktop',\
      'bitwarden.desktop',\
      'obsidian.desktop',\
      'code.desktop',\
      'org.gnome.Nautilus.desktop']"
  tags:
    - gnome

- name: Set Dash to Dock background color
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/background-color"
    value: "'{{ color.normal.black }}'"
  tags:
    - gnome

- name: Add laptop specific tasks
  include_tasks: laptop.yml
  when: target is defined and target == "laptop"
  tags:
    - gnome

#
# Shortcuts
#

- name: Set file browser shortcut
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/home"
    value: "['<Super>f']"
  tags:
    - gnome

- name: Set web browser shortcut
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/www"
    value: "['<Super>w']"
  tags:
    - gnome

- name: Set close window shortcut
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/close"
    value: "['<Super>k']"
  tags:
    - gnome

- name: Toggle fullscreen mode with Ctrl + \
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/toggle-fullscreen"
    value: "['<Primary>backslash']"
  tags:
    - gnome

- name: Use Ctrl+Super+Right to move window to next workspace
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-right"
    value: "['<Primary><Super>Right']"
  tags:
    - gnome

- name: Use Ctrl+Super+Left to move window to previous workspace
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-left"
    value: "['<Primary><Super>Left']"
  tags:
    - gnome

#
# Custom Shortcuts
#

- name: Create custom shortcut for `tilix --quake` command
  block:
    - name: Create custom shortcut name
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name"
        value: "'Tilix'"
    - name: Assign command to custom shortcut
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command"
        value: "'tilix --quake'"
    - name: Assign key binding to custom shortcut
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding"
        value: "'F12'"
  tags:
    - gnome

- name: Create a custom shortcut for Flameshot
  block:
    - name: Create custom shortcut name
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/name"
        value: "'Flameshot'"
    - name: Assign command to custom shortcut
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/command"
        value: "'flameshot gui'"
    - name: Assign key binding to custom shortcut
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/binding"
        value: "'<Super>Print'"
  tags:
    - gnome

  # All of your custom shortcuts must be added to an array.

- name: Enable custom shortcuts
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
    value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/']"
  tags:
    - gnome

#
# Gnome Terminal
#

- name: Set up Gnome terminal
  block:
    - name: Set terminal default size (columns)
      dconf:
        key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/default-size-columns"
        value: 120

    - name: Set terminal default size (rows)
      dconf:
        key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/default-size-rows"
        value: 30

    - name: Disable terminal bell
      dconf:
        key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/audible-bell"
        value: "false"

    - name: Hide scrollbar
      dconf:
        key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/scrollbar-policy"
        value: "'never'"

    - name: Enable custom font
      dconf:
        key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-system-font"
        value: "false"

    - name: Set custom font type and size
      dconf:
        key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/font"
        value: "'JetBrains Mono 10'"

    # Required so that we can set our own custom colors
    - name: Disable theme colors
      dconf:
        key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-theme-colors"
        value: "false"

    - name: Set background color
      dconf:
        key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/background-color"
        value: "'{{ color.normal.black }}'"

    - name: Set foreground color
      dconf:
        key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/foreground-color"
        value: "'{{ color.normal.green }}'"

    - name: Set background transparency
      dconf:
        key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/background-transparency-percent"
        value: "10"

    - name: Rename default profile
      dconf:
        key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/visible-name"
        value: "'Hak'"
  tags:
    - gnome
