---

#
# Standard Shortcuts
#

- name: Set web browser shortcut
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/www"
    value: "['<Super>w']"
  tags:
    - gnome

- name: Set close window shortcut
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/close"
    value: "['<Super>k']"
  tags:
    - gnome

- name: Toggle fullscreen mode with Super + \
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/toggle-fullscreen"
    value: "['<Super>backslash']"
  tags:
    - gnome

- name: Use Ctrl+Super+Right to switch to workspace to the right
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-left"
    value: "['<Primary><Super>Left']"
  tags:
    - gnome

- name: Use Ctrl+Super+Right to move window to workspace to the right
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-right"
    value: "['<Primary><Super>Right']"
  tags:
    - gnome

- name: Use Ctrl+Alt+Right to move window to workspace to the right
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-right"
    value: "['<Primary><Alt>Right']"
  tags:
    - gnome

- name: Use Ctrl+Alt+Left to move window to workspace to the left
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-left"
    value: "['<Primary><Alt>Left']"
  tags:
    - gnome

#
# Custom Shortcuts
#

- name: Create a custom shortcut for launching Flameshot
  block:
    - name: Create custom shortcut name
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name"
        value: "'Flameshot'"
    - name: Assign command to custom shortcut
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command"
        value: "'flameshot gui'"
    - name: Assign key binding to custom shortcut
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding"
        value: "'<Super>Print'"
  tags:
    - gnome

- name: Create custom shortcut for launching Nautilus
  block:
    - name: Create custom shortcut name
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/name"
        value: "'Nautilus'"
    - name: Assign command to custom shortcut
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/command"
        value: "'nautilus --new-window'"
    - name: Assign key binding to custom shortcut
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/binding"
        value: "'<Super>f'"
  tags:
    - gnome

- name: Create custom shortcut for launching Gnome Terminal
  block:
    - name: Create custom shortcut name
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/name"
        value: "'Gnome Terminal'"
    - name: Assign command to custom shortcut
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/command"
        value: "'gnome-terminal --window'"
    - name: Assign key binding to custom shortcut
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/binding"
        value: "'<Super>Return'"
  tags:
    - gnome

# All of our custom shortcuts must be added to an array
- name: Enable custom shortcuts
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
    value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/']"
  tags:
    - gnome
